### ISSUE TITLE
Crear documento: Guía de estudio de ética y deontología profesional

### ISSUE THREAD

**Issue by Roberto-Osores** [Roberto-Osores/Proyecto-ISPC#4]
Este issue se centra en la actividad grupal de crear un documento con los puntos importantes del material ofrecido en el bloque 1 del modulo programador.

**Comment by martinechava** [comment]
### ¿ QUE ES LA ETICA Y LA DEONTOLOGIA PROFESIONAL?
Cada una de las decisiones laborales que un/a profesional vinculado al área de la Tecnología  ha de tomar en el ámbito de las organizaciones impacta directa e indirectamente en el devenir de la empresa y en la calidad de vida laboral de quienes en ella se desempeñan. 
La asignatura contribuye a que se desarrollen la capacidad para reflexionar sobre su desempeño personal, social y laboral desde una perspectiva ética y ciudadana que le permita tomar decisiones como un sujeto responsable. 
Asimismo, se espera que desarrolle competencias para evaluar el cumplimiento de las leyes laborales y genere nuevas formas de actuar en el ámbito profesional ponderando la preservación del medio ambiente y la responsabilidad social empresarial. 
La visión que los y las estudiantes tendrá al incorporar los conocimientos de Ética y Deontología Profesional, es la lógica de la leyes con el mundo laboral relacionada con la informática que le permitirá comprender con mayor apertura intelectual los diferentes sectores y relaciones de la gestión de una organización de Redes e Infraestructuras en el mundo actual.
Ética en la Informática

**LA ÉTICA EN LA INFORMÁTICA** 
La ética es una disciplina filosófica que se define como "principios directivos que orientan a las personas en cuanto a la concepción de la vida, el hombre, los juicios, los hechos, y la moral”. 
La tecnología informática plantea nuevas situaciones y nuevos problemas y gran parte de estas nuevas situaciones y problemas son de una naturaleza ética; obviamente existen intentos de resolver estos problemas aplicando las actuales reglas y soluciones éticas de carácter general.
La deontología es la parte de la ética que trata sobre los deberes, especialmente relacionados con el ejercicio de una determinada profesión. Hace referencia a la ciencia o tratado de los deberes y normas éticas, que conciernen a los profesionales que a diario están en contacto con la tecnología y los medios masivos de comunicación como internet. 
Se trata la moral o ética profesional en el manejo del activo más importante que tienen las empresas, un bien cada vez más apreciado, que es la información.

**LOS PROBLEMAS ETICOS DE INTERNET**
En gran medida el desarrollo científico y tecnológico de este siglo ha sido impulsado por intereses vinculados con el afán de la hegemonía mundial de las grandes potencias, a las exigencias del desarrollo industrial, así como a las pautas de consumo que se producen y se difunden desde las sociedades que han marcado la avanzada en los procesos de modernización. 
Una enumeración somera de los problemas éticos del ciberespacio nos ofrece la siguiente lista:
La privacidad: no tanto la posibilidad de fallos en los sistemas de correo que provoquen mensajes que van a lugares equivocados, si no más bien la intromisión intencional. 
La Identidad: es posible esconder la verdadera identidad a la hora de intervenir en una conversación. 
La Inversa: la capacidad de manipulación se traslada de los mecanismos habituales a la sociedad a las habilidades de aquellos que manejan más el medio o que pueden intervenir de manera subrepticia en las comunicaciones ajenas.

Para seguir profundizando en el tema:
https://acceso.ispc.edu.ar/pluginfile.php/51705/mod_book/chapter/805/%C3%89tica%20y%20deontolog%C3%ADa%20inform%C3%A1tica%20conceptos%20b%C3%A1sicos.pdf?time=1651198880124

**MORAL VS. ETICA**
Ambos términos se usan de manera indistinta como si abarcarán el mismo significado pero no lo son. La ética es una rama de la filosofía y la moral forma parte de la vida diaria. 
La ética seria la moral pensada, mientras que la moral sería la moral vivida. Se trata de dos conceptos distintos, con diferentes etimologías y usos tanto en la vida privada como en la profesional y con distintos alcances en los múltiples planos de la sociedad contemporánea. 

Es la búsqueda del bien, de la realización personal en armonía con los seres humanos e implica una relación dinámica entre nuestros valores y los de la sociedad que nos haya tocado vivir. Intenta responder en la teoría y la práctica la pregunta de cómo debemos vivir, y desde un punto de vista académico, es la rama de la filosofía que estudia los principios morales, lo que es bueno y malo.

En el campo laboral existe la llamada ética laboral:
Honestidad, puntualidad sobriedad respeto etc. Y en muchas profesiones como la medicina, la docencia o el derecho existen los códigos éticos que pueden confundirse con los morales que se corresponden con el código de conducta del profesional.
La ética tiende a ser teórica y personal. Continuamente se pregunta por la naturaleza y el bien en las actividades humanas y sobre la validez de la moralidad en cada sociedad confrontada con valores que hemos dado por buenos y justos, como el derecho a la vida a la igualdad y a la libertad.
En este sentido podría decirse que la ética es constante, no suele cambiar con el tiempo regula el comportamiento humano desde cada persona y desde su propia conciencia.

La moral se refiere a los códigos de normas impuestos por una sociedad para regular la conducta o el comportamiento de los individuos. Abarca reglas tradiciones y valores compartidas por una sociedad en determinado momento de su historia. Se dice que una persona es moral cuando actúa de acuerdo a las normas costumbres y valores de su sociedad. Aunque estos pueden estar en contra de la ética de esa misma persona. La ética versa sobre lo que es bueno, mientras que la moral trata sobre lo que es obligatorio.
Los códigos morales se aplican a la vida cotidiana y a la conducta humana, nos dice como es el modo correcto de actuar en cada situación y lugar. En este sentido es la sociedad inmersa en una cultura determinada la que establece el código moral, por el que debe regirse todos sus integrantes. Faltar al código moral suele acarrear sanciones sociales, y penales en algunos casos.

La moral tiende a ser normativa a reflejarse en reglamentos y prohibiciones, como algunos preceptos recogidos en textos judeocristianos como los diez mandamientos. 
Forman parte de la moralidad las normas de comportamiento. Valores como la honradez, la discreción en el actuar y vestir, el respeto a la autoridad civil y el acatamiento de normas religiosas. 
La moralidad puede abarcar incluso aspectos de la dieta diaria y la higiene personal, como la prohibición total o parcial de consumir ciertos alimentos. 

Para seguir profundizando en el tema:
https://acceso.ispc.edu.ar/pluginfile.php/51705/mod_book/chapter/806/Moral%20vs%20%C3%89tica.pdf?time=1651199215856

**DILEMA DE LAS REDES SOCIALES**
La frase aparece en uno de los momentos más comentados del documental The Social Dilemma ("El dilema de las redes sociales"), que se estrenó en febrero de 2020 en el Festival de Cine de Sundance, en Estados Unidos, y que, siete meses después, se acaba de convertir en tema de conversación en el resto del mundo tras ser incluido en el catálogo de Netflix.

Según "El dilema de las redes sociales", experiencias digitales aparentemente triviales, como recomendaciones automáticas, notificaciones y publicaciones sugeridas, funcionarían como un cebo que es lanzado miles de millones de veces al día por las aplicaciones más populares del planeta. El objetivo sería acaparar el tiempo de las personas, una moneda valiosa para empresas, políticos, organizaciones o países que quieran vender productos o ideas a audiencias vulnerables e hipersegmentadas. 
Elogiado por detallar herramientas y estrategias sofisticadas en un lenguaje accesible a grandes audiencias, recibe críticas por no ofrecer soluciones a los problemas enumerados y por ser presentada por personas con características similares: buena parte de los entrevistados son exejecutivos: hombres jóvenes, ricos y blancos.

"Si no pagas por el producto, el producto eres tú"

Explican que cuantas más horas pasa un usuario conectado a sus redes sociales, más información detallada sobre hábitos, gustos y características de consumo acaba exponiendo. Estos datos son recopilados y organizados mediante algoritmos que mapean los me gusta y los comentarios, analizan los tiempos de lectura y la exposición a las imágenes, y alimentan enormes servidores.
Luego, se ofrece información sobre los usuarios a los clientes, desde marcas de cosméticos y universidades hasta políticos y gobiernos, que pagan millones de dólares por mostrar productos o ideas a audiencias que estén dispuestas a participar. Sin embargo, el engranaje solo funciona si los usuarios permanecen conectados a sus perfiles y, por lo tanto, pueden estar expuestos al máximo número de anuncios.

Una de las más claras estrategias sería el desplazamiento automático, una estrategia desarrollada para que la experiencia de red no tenga fin y el usuario permanezca conectado. 
Las notificaciones, a su vez, se describen como una de las herramientas más eficaces para atraer a los que están fuera y mantener a los que ya están conectados. 
La dinámica de "me gusta" y comentarios con elogios o críticas se estimularía para manipular y hacer dependientes a los usuarios, según los entrevistados. Estos "chupetes digitales" son las validaciones recibidas por elogios, y aportan un sentimiento de felicidad o logro a los usuarios. "Eso va atrofiando nuestra capacidad de afrontar las cosas".

“Las noticias falsas se propagan 6 veces más rápido que las verdaderas”

"Creamos un sistema que privilegia la información falsa porque la información falsa rinde más dinero a las empresas que la verdad", "la verdad es aburrida".

Consejos para protegerse 
a) Las notificaciones serían la principal herramienta de manipulación en las redes. La sugerencia de los entrevistados es deshabilitarlas, para acceder la red social cuando uno lo desee, y no al revés. 
b) No embarcarse en las recomendaciones de videos o contenidos sin reflexionar. 
c) Sigue a personas o páginas con las que no estás de acuerdo. 
d) Desconecta una hora antes de acostarse. Deja tu teléfono, tableta y computadora portátil en otra habitación y en modo avión. 
e) Valora tus clics y tu tiempo. 

Para seguir profundizando en el tema:
https://acceso.ispc.edu.ar/pluginfile.php/51705/mod_book/chapter/815/Dilema%20en%20las%20redes%20sociales.pdf
https://cuevana.se/pelicula/el-dilema-de-las-redes-sociales/
https://www.netflix.com/ar/title/81254224
